# This is a TOML Config for my REST-API app
# Created by Catborisovv (c) 2020-2024

# Конфигурация HTTP-Сервера
[HttpSrv]
Host = "localhost"
Port = 7777

# Конфигурация Базы-Данных PostgreSQL
[DataBase]
DB_USER = ""
DB_PASS = ""
DB_NAME = ""